name: dstmobileapp
description: "Supporting SME Sales."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.6.6
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/thr.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/thr.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
